name: CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a long running process
        run: |
          yes helloooworld
          for sig in 1 2 3 6 9 14 15; do
          trap 'echo "caught signal '$sig'..."' $sig
          done
        
